//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using ContactBusinessEntities;

namespace ContactDataAccess
{
    public partial class ContactEntities : ObjectContext
    {
        public const string ConnectionString = "name=ContactEntities";
        public const string ContainerName = "ContactEntities";
    
        #region Constructors
    
        public ContactEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ContactEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ContactEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Contact> Contacts
        {
            get { return _contacts  ?? (_contacts = CreateObjectSet<Contact>("Contacts")); }
        }
        private ObjectSet<Contact> _contacts;

        #endregion
    }
}
